<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\RecipeCategory;
use App\Models\RecipePost;

class KoreanRecipeSeeder extends Seeder
{
    public function run(): void
    {
        // ── 1. 카테고리 생성/업데이트 (한글 이름 추가) ──
        $categories = [
            ['name' => 'Stew & Soup',  'name_ko' => '찌개/탕',  'key' => 'stew',      'icon' => "\xF0\x9F\x8D\xB2", 'sort_order' => 1],
            ['name' => 'Stir-fry',     'name_ko' => '볶음',     'key' => 'stirfry',   'icon' => "\xF0\x9F\x8D\xB3", 'sort_order' => 2],
            ['name' => 'Grill',        'name_ko' => '구이',     'key' => 'grill',     'icon' => "\xF0\x9F\x94\xA5", 'sort_order' => 3],
            ['name' => 'Rice & Porridge','name_ko' => '밥/죽',  'key' => 'rice',      'icon' => "\xF0\x9F\x8D\x9A", 'sort_order' => 4],
            ['name' => 'Noodles',      'name_ko' => '면',       'key' => 'noodle',    'icon' => "\xF0\x9F\x8D\x9C", 'sort_order' => 5],
            ['name' => 'Side Dish',    'name_ko' => '반찬',     'key' => 'side',      'icon' => "\xF0\x9F\xA5\x97", 'sort_order' => 6],
            ['name' => 'Kimchi',       'name_ko' => '김치',     'key' => 'kimchi',    'icon' => "\xF0\x9F\xA5\xAC", 'sort_order' => 7],
            ['name' => 'Dessert',      'name_ko' => '디저트',   'key' => 'dessert',   'icon' => "\xF0\x9F\x8D\xA1", 'sort_order' => 8],
            ['name' => 'Street Food',  'name_ko' => '분식',     'key' => 'street',    'icon' => "\xF0\x9F\xA2\x81", 'sort_order' => 9],
            ['name' => 'Korean BBQ',   'name_ko' => '한식BBQ',  'key' => 'bbq',       'icon' => "\xF0\x9F\xA5\xA9", 'sort_order' => 10],
        ];

        $categoryMap = [];
        foreach ($categories as $cat) {
            $existing = RecipeCategory::where('key', $cat['key'])->first();
            if ($existing) {
                $existing->update(['name_ko' => $cat['name_ko'], 'icon' => $cat['icon'], 'sort_order' => $cat['sort_order']]);
                $categoryMap[$cat['key']] = $existing->id;
            } else {
                $created = RecipeCategory::create($cat);
                $categoryMap[$cat['key']] = $created->id;
            }
        }

        // ── 2. 한국 요리 50+ 레시피 ──
        $recipes = [
            // ===== 찌개/탕 =====
            [
                'category' => 'stew',
                'title' => 'Kimchi Jjigae',
                'title_ko' => '김치찌개',
                'intro' => 'Classic Korean kimchi stew with pork and tofu',
                'intro_ko' => '잘 익은 김치로 만드는 얼큰한 김치찌개. 돼지고기와 두부가 들어가 든든한 한 끼가 됩니다.',
                'difficulty' => '쉬움',
                'cook_time' => '30분',
                'calories' => 350,
                'servings' => 2,
                'ingredients' => [
                    ['name' => 'Aged kimchi', 'amount' => '2 cups'],
                    ['name' => 'Pork belly', 'amount' => '150g'],
                    ['name' => 'Tofu', 'amount' => '1/2 block'],
                    ['name' => 'Green onion', 'amount' => '2 stalks'],
                    ['name' => 'Gochugaru', 'amount' => '1 tbsp'],
                    ['name' => 'Garlic', 'amount' => '3 cloves'],
                ],
                'ingredients_ko' => [
                    ['name' => '묵은지', 'amount' => '2컵'],
                    ['name' => '삼겹살', 'amount' => '150g'],
                    ['name' => '두부', 'amount' => '1/2모'],
                    ['name' => '대파', 'amount' => '2대'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '3쪽'],
                ],
                'steps' => [
                    'Slice pork belly and stir-fry in pot until browned.',
                    'Add chopped kimchi and stir-fry for 3 minutes.',
                    'Add water and bring to boil.',
                    'Add tofu and green onion, simmer for 15 minutes.',
                ],
                'steps_ko' => [
                    '삼겹살을 얇게 썰어 냄비에서 볶아 기름을 뺍니다.',
                    '김치를 적당한 크기로 잘라 넣고 3분간 함께 볶습니다.',
                    '물을 넣고 끓어오르면 중불로 줄입니다.',
                    '두부를 넣고 대파를 썰어 넣은 뒤 15분간 끓입니다.',
                ],
                'tips' => ['Use well-fermented kimchi for best flavor.'],
                'tips_ko' => ['묵은지를 사용하면 국물이 더 깊고 진해집니다.', '참치캔을 넣으면 감칠맛이 더해집니다.'],
                'tags' => ['김치찌개', '찌개', '한식', '겨울음식'],
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Korean_stew-Kimchi_jjigae-05.jpg/1200px-Korean_stew-Kimchi_jjigae-05.jpg',
            ],
            [
                'category' => 'stew',
                'title' => 'Doenjang Jjigae',
                'title_ko' => '된장찌개',
                'intro_ko' => '구수한 된장으로 끓인 한국의 대표적인 찌개입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '25분',
                'calories' => 280,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '된장', 'amount' => '2큰술'],
                    ['name' => '두부', 'amount' => '1/2모'],
                    ['name' => '애호박', 'amount' => '1/3개'],
                    ['name' => '양파', 'amount' => '1/4개'],
                    ['name' => '청양고추', 'amount' => '1개'],
                    ['name' => '대파', 'amount' => '1대'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '멸치육수', 'amount' => '2컵'],
                ],
                'steps_ko' => [
                    '멸치육수를 끓입니다.',
                    '된장을 풀어넣고 감자, 호박, 양파를 넣습니다.',
                    '끓어오르면 두부와 고추를 넣고 5분 더 끓입니다.',
                    '대파와 마늘을 넣고 마무리합니다.',
                ],
                'tips_ko' => ['멸치와 다시마로 육수를 내면 깊은 맛이 납니다.'],
                'tags' => ['된장찌개', '찌개', '한식', '건강식'],
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Korean_stew-Doenjang_jjigae-05.jpg/1200px-Korean_stew-Doenjang_jjigae-05.jpg',
            ],
            [
                'category' => 'stew',
                'title' => 'Sundubu Jjigae',
                'title_ko' => '순두부찌개',
                'intro_ko' => '부드러운 순두부와 얼큰한 양념의 조화. 계란을 풀어 먹으면 더 맛있습니다.',
                'difficulty' => '쉬움',
                'cook_time' => '20분',
                'calories' => 310,
                'servings' => 1,
                'ingredients_ko' => [
                    ['name' => '순두부', 'amount' => '1봉'],
                    ['name' => '바지락', 'amount' => '1/2컵'],
                    ['name' => '계란', 'amount' => '1개'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '뚝배기에 참기름을 두르고 고춧가루와 마늘을 볶습니다.',
                    '물과 바지락을 넣고 끓입니다.',
                    '순두부를 넣고 5분간 끓입니다.',
                    '계란을 깨넣고 뚜껑을 덮어 1분간 뜸들입니다.',
                ],
                'tips_ko' => ['해물을 넣으면 국물이 더 시원해집니다.'],
                'tags' => ['순두부찌개', '찌개', '한식', '매운음식'],
            ],
            [
                'category' => 'stew',
                'title' => 'Budae Jjigae',
                'title_ko' => '부대찌개',
                'intro_ko' => '소시지, 햄, 라면, 김치 등이 어우러진 퓨전 찌개입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 520,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '소시지', 'amount' => '4개'],
                    ['name' => '스팸', 'amount' => '1/2캔'],
                    ['name' => '라면사리', 'amount' => '1개'],
                    ['name' => '김치', 'amount' => '1컵'],
                    ['name' => '두부', 'amount' => '1/2모'],
                    ['name' => '떡', 'amount' => '1줌'],
                    ['name' => '고춧가루', 'amount' => '2큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '넓은 냄비에 재료를 가지런히 담습니다.',
                    '양념장(고춧가루, 고추장, 간장, 설탕, 마늘)을 만듭니다.',
                    '육수를 부어 끓입니다.',
                    '라면사리를 넣고 3분 더 끓입니다.',
                ],
                'tips_ko' => ['치즈를 올려 먹으면 더 맛있습니다.'],
                'tags' => ['부대찌개', '찌개', '퓨전', '모임음식'],
            ],
            [
                'category' => 'stew',
                'title' => 'Gamjatang',
                'title_ko' => '감자탕',
                'intro_ko' => '돼지 등뼈와 감자를 넣고 푹 끓인 얼큰한 탕입니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간 이상',
                'calories' => 480,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '돼지등뼈', 'amount' => '1kg'],
                    ['name' => '감자', 'amount' => '3개'],
                    ['name' => '우거지', 'amount' => '1줌'],
                    ['name' => '깻잎', 'amount' => '10장'],
                    ['name' => '된장', 'amount' => '1큰술'],
                    ['name' => '고춧가루', 'amount' => '3큰술'],
                ],
                'steps_ko' => [
                    '등뼈를 찬물에 2시간 담가 핏물을 뺍니다.',
                    '큰 냄비에 등뼈와 물을 넣고 1시간 끓입니다.',
                    '감자, 우거지, 양념을 넣고 30분 더 끓입니다.',
                    '들깻가루와 깻잎을 넣고 마무리합니다.',
                ],
                'tags' => ['감자탕', '탕', '한식', '겨울음식', '보양식'],
            ],
            [
                'category' => 'stew',
                'title' => 'Samgyetang',
                'title_ko' => '삼계탕',
                'intro_ko' => '인삼과 찹쌀을 넣은 닭백숙. 여름 보양식의 대명사입니다.',
                'difficulty' => '보통',
                'cook_time' => '1시간',
                'calories' => 600,
                'servings' => 1,
                'ingredients_ko' => [
                    ['name' => '영계(작은 닭)', 'amount' => '1마리'],
                    ['name' => '찹쌀', 'amount' => '1/3컵'],
                    ['name' => '인삼', 'amount' => '1뿌리'],
                    ['name' => '대추', 'amount' => '3개'],
                    ['name' => '마늘', 'amount' => '5쪽'],
                ],
                'steps_ko' => [
                    '닭 뱃속에 찹쌀, 인삼, 대추, 마늘을 넣습니다.',
                    '냄비에 닭을 넣고 물을 부어 끓입니다.',
                    '끓어오르면 약불로 줄여 1시간 끓입니다.',
                    '소금과 후추로 간을 합니다.',
                ],
                'tips_ko' => ['압력솥을 사용하면 30분 만에 완성할 수 있습니다.'],
                'tags' => ['삼계탕', '탕', '보양식', '여름음식'],
            ],

            // ===== 볶음 =====
            [
                'category' => 'stirfry',
                'title' => 'Tteokbokki',
                'title_ko' => '떡볶이',
                'intro_ko' => '매콤달콤한 고추장 양념의 떡볶이. 한국 길거리 음식의 대표주자입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '20분',
                'calories' => 380,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '떡볶이떡', 'amount' => '300g'],
                    ['name' => '어묵', 'amount' => '2장'],
                    ['name' => '고추장', 'amount' => '2큰술'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '설탕', 'amount' => '1큰술'],
                    ['name' => '간장', 'amount' => '1큰술'],
                    ['name' => '대파', 'amount' => '1대'],
                ],
                'steps_ko' => [
                    '물 2컵에 고추장, 고춧가루, 설탕, 간장을 풀어 양념장을 만듭니다.',
                    '양념장을 끓인 후 떡을 넣습니다.',
                    '어묵을 넣고 중불에서 떡이 말랑해질 때까지 졸입니다.',
                    '대파를 넣고 1분 더 끓여 완성합니다.',
                ],
                'tips_ko' => ['삶은 계란을 곁들이면 더 맛있습니다.', '치즈를 올려도 좋습니다.'],
                'tags' => ['떡볶이', '분식', '매운음식', '길거리음식'],
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Tteok-bokki.jpg/1200px-Tteok-bokki.jpg',
            ],
            [
                'category' => 'stirfry',
                'title' => 'Japchae',
                'title_ko' => '잡채',
                'intro_ko' => '당면과 채소를 참기름에 볶은 잔치 음식. 명절과 생일상에 빠지지 않습니다.',
                'difficulty' => '보통',
                'cook_time' => '40분',
                'calories' => 420,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '당면', 'amount' => '200g'],
                    ['name' => '시금치', 'amount' => '1줌'],
                    ['name' => '당근', 'amount' => '1/2개'],
                    ['name' => '양파', 'amount' => '1/2개'],
                    ['name' => '표고버섯', 'amount' => '3개'],
                    ['name' => '소고기', 'amount' => '100g'],
                    ['name' => '간장', 'amount' => '3큰술'],
                    ['name' => '참기름', 'amount' => '2큰술'],
                    ['name' => '설탕', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '당면을 삶아 찬물에 헹구고 참기름을 넣어 버무립니다.',
                    '각 채소와 소고기를 따로따로 볶습니다.',
                    '큰 볼에 당면과 볶은 재료를 모두 넣습니다.',
                    '간장, 참기름, 설탕, 깨를 넣고 잘 버무립니다.',
                ],
                'tips_ko' => ['재료를 따로 볶아야 색이 살고 맛이 좋습니다.'],
                'tags' => ['잡채', '볶음', '명절음식', '잔치음식'],
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Japchae.jpg/1200px-Japchae.jpg',
            ],
            [
                'category' => 'stirfry',
                'title' => 'Dakgalbi',
                'title_ko' => '닭갈비',
                'intro_ko' => '매콤한 양념에 재운 닭고기와 채소를 볶은 춘천 명물 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '35분',
                'calories' => 450,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '닭다리살', 'amount' => '400g'],
                    ['name' => '양배추', 'amount' => '1/4개'],
                    ['name' => '고구마', 'amount' => '1개'],
                    ['name' => '떡', 'amount' => '1줌'],
                    ['name' => '고추장', 'amount' => '3큰술'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '간장', 'amount' => '2큰술'],
                    ['name' => '카레가루', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '닭다리살을 한입 크기로 자르고 양념에 30분 재웁니다.',
                    '팬에 닭고기를 먼저 볶습니다.',
                    '양배추, 고구마, 떡을 넣고 뚜껑을 덮어 익힙니다.',
                    '볶아가며 양념이 골고루 배게 합니다.',
                ],
                'tips_ko' => ['마지막에 치즈와 볶음밥을 만들어 먹으면 최고입니다.'],
                'tags' => ['닭갈비', '볶음', '춘천', '매운음식'],
            ],
            [
                'category' => 'stirfry',
                'title' => 'Ojingeo Bokkeum',
                'title_ko' => '오징어볶음',
                'intro_ko' => '매콤한 양념에 오징어와 채소를 볶은 밥반찬용 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '20분',
                'calories' => 280,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '오징어', 'amount' => '1마리'],
                    ['name' => '양파', 'amount' => '1/2개'],
                    ['name' => '당근', 'amount' => '1/3개'],
                    ['name' => '고추장', 'amount' => '2큰술'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '간장', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '오징어를 깨끗이 손질하여 먹기 좋은 크기로 자릅니다.',
                    '양념장(고추장, 고춧가루, 간장, 설탕, 마늘)을 만듭니다.',
                    '팬에 기름을 두르고 채소를 먼저 볶습니다.',
                    '오징어와 양념장을 넣고 센 불에서 빠르게 볶습니다.',
                ],
                'tags' => ['오징어볶음', '볶음', '밥반찬', '매운음식'],
            ],
            [
                'category' => 'stirfry',
                'title' => 'Kimchi Bokkeumbap',
                'title_ko' => '김치볶음밥',
                'intro_ko' => '김치와 밥을 볶아 만드는 간단한 한 끼 식사입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '15분',
                'calories' => 420,
                'servings' => 1,
                'ingredients_ko' => [
                    ['name' => '밥', 'amount' => '1공기'],
                    ['name' => '김치', 'amount' => '1컵'],
                    ['name' => '참치캔', 'amount' => '1/2캔'],
                    ['name' => '계란', 'amount' => '1개'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                    ['name' => '김가루', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '김치를 잘게 썰어 팬에 볶습니다.',
                    '참치를 넣고 함께 볶습니다.',
                    '밥을 넣고 참기름을 둘러 볶습니다.',
                    '접시에 담고 계란프라이와 김가루를 올립니다.',
                ],
                'tags' => ['김치볶음밥', '볶음밥', '간편식', '혼밥'],
            ],

            // ===== 구이 =====
            [
                'category' => 'grill',
                'title' => 'Bulgogi',
                'title_ko' => '불고기',
                'intro_ko' => '달콤한 간장 양념에 재운 소고기 구이. 한국을 대표하는 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 400,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '소고기(불고기용)', 'amount' => '400g'],
                    ['name' => '배', 'amount' => '1/4개'],
                    ['name' => '간장', 'amount' => '4큰술'],
                    ['name' => '설탕', 'amount' => '2큰술'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '2큰술'],
                    ['name' => '양파', 'amount' => '1개'],
                    ['name' => '대파', 'amount' => '1대'],
                ],
                'steps_ko' => [
                    '배를 갈아서 간장, 설탕, 참기름, 마늘과 섞어 양념장을 만듭니다.',
                    '소고기를 양념장에 30분 이상 재웁니다.',
                    '팬이나 그릴에서 센 불로 빠르게 구워냅니다.',
                    '채소와 함께 볶아도 맛있습니다.',
                ],
                'tips_ko' => ['키위나 배를 갈아 넣으면 고기가 더 연해집니다.'],
                'tags' => ['불고기', '구이', '한식', '소고기'],
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Korean_BBQ-Bulgogi-01.jpg/1200px-Korean_BBQ-Bulgogi-01.jpg',
            ],
            [
                'category' => 'grill',
                'title' => 'Samgyeopsal',
                'title_ko' => '삼겹살 구이',
                'intro_ko' => '두꺼운 삼겹살을 구워 쌈채소에 싸먹는 한국식 바비큐입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '20분',
                'calories' => 550,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '삼겹살', 'amount' => '400g'],
                    ['name' => '상추', 'amount' => '1봉'],
                    ['name' => '깻잎', 'amount' => '10장'],
                    ['name' => '쌈장', 'amount' => '적당량'],
                    ['name' => '마늘', 'amount' => '10쪽'],
                    ['name' => '고추', 'amount' => '2개'],
                ],
                'steps_ko' => [
                    '삼겹살을 적당한 두께로 자릅니다.',
                    '달군 팬이나 그릴에서 앞뒤로 노릇하게 굽습니다.',
                    '마늘도 함께 구워줍니다.',
                    '상추와 깻잎에 삼겹살, 마늘, 쌈장을 올려 싸먹습니다.',
                ],
                'tips_ko' => ['소금을 참기름에 섞어 찍어 먹어도 맛있습니다.'],
                'tags' => ['삼겹살', '구이', '한식', '회식음식'],
            ],
            [
                'category' => 'grill',
                'title' => 'Galbi',
                'title_ko' => 'LA갈비',
                'intro_ko' => '달콤짭짤한 양념에 재운 소갈비. 명절과 생일상의 필수 메뉴입니다.',
                'difficulty' => '보통',
                'cook_time' => '45분',
                'calories' => 580,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => 'LA갈비', 'amount' => '1kg'],
                    ['name' => '간장', 'amount' => '6큰술'],
                    ['name' => '설탕', 'amount' => '3큰술'],
                    ['name' => '배즙', 'amount' => '3큰술'],
                    ['name' => '참기름', 'amount' => '2큰술'],
                    ['name' => '다진마늘', 'amount' => '2큰술'],
                    ['name' => '후추', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '갈비를 찬물에 1시간 담가 핏물을 뺍니다.',
                    '양념장을 만들어 갈비를 4시간 이상 재웁니다.',
                    '그릴이나 팬에서 중불로 구워냅니다.',
                    '양면이 노릇하게 구워지면 완성입니다.',
                ],
                'tags' => ['갈비', '구이', '명절음식', '소고기'],
            ],
            [
                'category' => 'grill',
                'title' => 'Jeyuk Bokkeum',
                'title_ko' => '제육볶음',
                'intro_ko' => '매콤한 고추장 양념에 볶은 돼지고기 요리입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '25분',
                'calories' => 450,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '돼지 앞다리살', 'amount' => '300g'],
                    ['name' => '고추장', 'amount' => '2큰술'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '간장', 'amount' => '1큰술'],
                    ['name' => '양파', 'amount' => '1/2개'],
                    ['name' => '대파', 'amount' => '1대'],
                    ['name' => '생강즙', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '돼지고기를 양념장에 20분 재웁니다.',
                    '센 불에 팬을 달궈 고기를 볶습니다.',
                    '양파와 대파를 넣고 함께 볶습니다.',
                    '불을 끄고 깨를 뿌려 완성합니다.',
                ],
                'tags' => ['제육볶음', '볶음', '매운음식', '밥도둑'],
            ],

            // ===== 밥/죽 =====
            [
                'category' => 'rice',
                'title' => 'Bibimbap',
                'title_ko' => '비빔밥',
                'intro_ko' => '밥 위에 각종 나물과 고추장을 올려 비벼 먹는 한국의 대표 음식입니다.',
                'difficulty' => '보통',
                'cook_time' => '40분',
                'calories' => 500,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '밥', 'amount' => '2공기'],
                    ['name' => '시금치나물', 'amount' => '1줌'],
                    ['name' => '콩나물', 'amount' => '1줌'],
                    ['name' => '당근', 'amount' => '1/2개'],
                    ['name' => '표고버섯', 'amount' => '3개'],
                    ['name' => '소고기', 'amount' => '100g'],
                    ['name' => '계란', 'amount' => '2개'],
                    ['name' => '고추장', 'amount' => '2큰술'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '각 채소를 데치거나 볶아 나물을 준비합니다.',
                    '소고기를 양념하여 볶습니다.',
                    '그릇에 밥을 담고 나물, 고기, 계란프라이를 올립니다.',
                    '고추장과 참기름을 넣고 비벼 먹습니다.',
                ],
                'tips_ko' => ['돌솥에 밥을 담으면 누룽지가 생겨 더 맛있습니다.'],
                'tags' => ['비빔밥', '밥', '한식', '건강식', '전주'],
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Dolsot-bibimbap.jpg/1200px-Dolsot-bibimbap.jpg',
            ],
            [
                'category' => 'rice',
                'title' => 'Gimbap',
                'title_ko' => '김밥',
                'intro_ko' => '밥과 다양한 재료를 김으로 말아 만드는 한국식 롤입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 350,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '밥', 'amount' => '2공기'],
                    ['name' => '김', 'amount' => '4장'],
                    ['name' => '단무지', 'amount' => '2줄'],
                    ['name' => '시금치', 'amount' => '1줌'],
                    ['name' => '당근', 'amount' => '1/2개'],
                    ['name' => '계란', 'amount' => '2개'],
                    ['name' => '햄', 'amount' => '1줄'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '밥에 참기름과 소금을 넣어 비벼둡니다.',
                    '시금치를 데치고, 당근과 계란말이를 준비합니다.',
                    '김 위에 밥을 얇게 펴고 재료를 올립니다.',
                    '김발을 이용해 단단히 말아 먹기 좋게 자릅니다.',
                ],
                'tips_ko' => ['밥을 너무 두껍게 펴면 터질 수 있으니 얇게 펴세요.'],
                'tags' => ['김밥', '도시락', '소풍음식', '한식'],
            ],
            [
                'category' => 'rice',
                'title' => 'Juk (Porridge)',
                'title_ko' => '호박죽',
                'intro_ko' => '달콤하고 부드러운 호박죽. 속이 편안해지는 보양음식입니다.',
                'difficulty' => '보통',
                'cook_time' => '45분',
                'calories' => 200,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '늙은호박', 'amount' => '1/4개'],
                    ['name' => '찹쌀가루', 'amount' => '3큰술'],
                    ['name' => '설탕', 'amount' => '2큰술'],
                    ['name' => '소금', 'amount' => '약간'],
                    ['name' => '팥', 'amount' => '1/2컵 (선택)'],
                ],
                'steps_ko' => [
                    '호박을 쪄서 부드럽게 으깹니다.',
                    '물을 넣고 끓이다가 찹쌀가루물을 넣어 농도를 맞춥니다.',
                    '설탕과 소금으로 간을 합니다.',
                    '경단이나 팥을 올려 완성합니다.',
                ],
                'tags' => ['호박죽', '죽', '보양식', '겨울음식'],
            ],
            [
                'category' => 'rice',
                'title' => 'Kongnamul Bap',
                'title_ko' => '콩나물밥',
                'intro_ko' => '콩나물과 함께 지은 밥에 양념장을 비벼 먹는 소박한 한 끼입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '30분',
                'calories' => 320,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '쌀', 'amount' => '2컵'],
                    ['name' => '콩나물', 'amount' => '2줌'],
                    ['name' => '간장', 'amount' => '2큰술'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '대파', 'amount' => '1대'],
                ],
                'steps_ko' => [
                    '쌀을 씻어 밥솥에 넣고 콩나물을 올립니다.',
                    '평소보다 물을 약간 적게 잡아 밥을 짓습니다.',
                    '양념장(간장, 참기름, 고춧가루, 대파, 깨)을 만듭니다.',
                    '밥이 완성되면 양념장을 넣고 비벼 먹습니다.',
                ],
                'tags' => ['콩나물밥', '밥', '간편식', '건강식'],
            ],

            // ===== 면 =====
            [
                'category' => 'noodle',
                'title' => 'Jajangmyeon',
                'title_ko' => '짜장면',
                'intro_ko' => '춘장 소스에 돼지고기와 양파를 볶아 면에 올린 한국식 중화 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 550,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '중화면', 'amount' => '2인분'],
                    ['name' => '춘장', 'amount' => '4큰술'],
                    ['name' => '돼지고기', 'amount' => '150g'],
                    ['name' => '양파', 'amount' => '2개'],
                    ['name' => '감자', 'amount' => '1개'],
                    ['name' => '애호박', 'amount' => '1/3개'],
                ],
                'steps_ko' => [
                    '채소를 깍둑 썰고 돼지고기도 작게 썹니다.',
                    '기름에 춘장을 볶아 탄맛을 줄입니다.',
                    '고기와 채소를 볶은 후 물을 넣고 끓입니다.',
                    '전분물로 농도를 맞추고 삶은 면 위에 올립니다.',
                ],
                'tags' => ['짜장면', '면', '중화요리', '블랙데이'],
            ],
            [
                'category' => 'noodle',
                'title' => 'Naengmyeon',
                'title_ko' => '냉면',
                'intro_ko' => '시원한 육수에 메밀면을 말아 먹는 여름 대표 음식입니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간 이상',
                'calories' => 380,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '냉면 사리', 'amount' => '2인분'],
                    ['name' => '소고기(양지)', 'amount' => '300g'],
                    ['name' => '동치미 국물', 'amount' => '2컵'],
                    ['name' => '식초', 'amount' => '1큰술'],
                    ['name' => '겨자', 'amount' => '1큰술'],
                    ['name' => '삶은 계란', 'amount' => '1개'],
                    ['name' => '오이', 'amount' => '1/2개'],
                    ['name' => '배', 'amount' => '1/4개'],
                ],
                'steps_ko' => [
                    '소고기를 삶아 육수를 만들고 차갑게 식힙니다.',
                    '육수에 동치미 국물을 섞어 간을 맞춥니다.',
                    '냉면 사리를 삶아 찬물에 헹구어 그릇에 담습니다.',
                    '차가운 육수를 붓고 계란, 오이, 배를 올립니다.',
                ],
                'tips_ko' => ['육수를 얼려서 살짝 샤베트 상태로 내면 더 시원합니다.'],
                'tags' => ['냉면', '면', '여름음식', '시원한음식'],
            ],
            [
                'category' => 'noodle',
                'title' => 'Kalguksu',
                'title_ko' => '칼국수',
                'intro_ko' => '손으로 밀어 칼로 자른 면을 맑은 국물에 담근 따뜻한 면 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '40분',
                'calories' => 400,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '칼국수면', 'amount' => '2인분'],
                    ['name' => '바지락', 'amount' => '1컵'],
                    ['name' => '애호박', 'amount' => '1/3개'],
                    ['name' => '감자', 'amount' => '1개'],
                    ['name' => '대파', 'amount' => '1대'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '바지락을 깨끗이 씻어 육수를 냅니다.',
                    '감자를 넣어 끓이다가 면을 넣습니다.',
                    '호박과 대파를 넣고 면이 익을 때까지 끓입니다.',
                    '소금으로 간을 하고 완성합니다.',
                ],
                'tags' => ['칼국수', '면', '한식', '겨울음식'],
            ],
            [
                'category' => 'noodle',
                'title' => 'Japchae Bap',
                'title_ko' => '비빔국수',
                'intro_ko' => '매콤달콤한 양념장에 소면을 비벼 먹는 여름 별미입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '15분',
                'calories' => 350,
                'servings' => 1,
                'ingredients_ko' => [
                    ['name' => '소면', 'amount' => '1인분'],
                    ['name' => '고추장', 'amount' => '2큰술'],
                    ['name' => '식초', 'amount' => '1큰술'],
                    ['name' => '설탕', 'amount' => '1큰술'],
                    ['name' => '오이', 'amount' => '1/3개'],
                    ['name' => '삶은계란', 'amount' => '1개'],
                ],
                'steps_ko' => [
                    '소면을 삶아 찬물에 헹굽니다.',
                    '양념장(고추장, 식초, 설탕, 참기름, 깨)을 만듭니다.',
                    '면에 양념장을 넣고 비빕니다.',
                    '오이채와 계란을 올려 완성합니다.',
                ],
                'tags' => ['비빔국수', '면', '여름음식', '간편식'],
            ],

            // ===== 반찬 =====
            [
                'category' => 'side',
                'title' => 'Gyeran Mari',
                'title_ko' => '계란말이',
                'intro_ko' => '채소를 넣어 돌돌 말아 만든 계란말이. 도시락과 밥반찬의 필수입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '10분',
                'calories' => 180,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '계란', 'amount' => '4개'],
                    ['name' => '당근', 'amount' => '약간'],
                    ['name' => '대파', 'amount' => '약간'],
                    ['name' => '소금', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '계란을 풀고 잘게 썬 당근, 대파를 넣습니다.',
                    '소금으로 간을 합니다.',
                    '기름 두른 팬에 계란물을 얇게 붓고 돌돌 말아줍니다.',
                    '3-4번 반복하여 두툼하게 완성합니다.',
                ],
                'tags' => ['계란말이', '반찬', '도시락', '간편식'],
            ],
            [
                'category' => 'side',
                'title' => 'Japchae Bap',
                'title_ko' => '잡채밥',
                'intro_ko' => '잡채를 밥 위에 올려 한 그릇으로 즐기는 메뉴입니다.',
                'difficulty' => '보통',
                'cook_time' => '40분',
                'calories' => 480,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '밥', 'amount' => '2공기'],
                    ['name' => '당면', 'amount' => '100g'],
                    ['name' => '시금치', 'amount' => '1줌'],
                    ['name' => '당근', 'amount' => '1/3개'],
                    ['name' => '소고기', 'amount' => '50g'],
                ],
                'steps_ko' => [
                    '당면을 삶고, 채소와 고기를 각각 볶습니다.',
                    '간장, 참기름으로 양념합니다.',
                    '모든 재료를 섞어 잡채를 만듭니다.',
                    '밥 위에 올려 완성합니다.',
                ],
                'tags' => ['잡채밥', '밥', '한식'],
            ],
            [
                'category' => 'side',
                'title' => 'Sigeumchi Namul',
                'title_ko' => '시금치나물',
                'intro_ko' => '시금치를 참기름과 마늘로 무친 기본 나물 반찬입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '10분',
                'calories' => 60,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '시금치', 'amount' => '1봉'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '소금', 'amount' => '약간'],
                    ['name' => '깨', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '시금치를 깨끗이 씻어 끓는 물에 살짝 데칩니다.',
                    '찬물에 헹궈 물기를 꼭 짭니다.',
                    '참기름, 마늘, 소금, 깨로 조물조물 무칩니다.',
                ],
                'tags' => ['시금치나물', '나물', '반찬', '건강식'],
            ],
            [
                'category' => 'side',
                'title' => 'Eomuk Bokkeum',
                'title_ko' => '어묵볶음',
                'intro_ko' => '어묵을 간장 양념에 볶은 간편한 밥반찬입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '10분',
                'calories' => 150,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '어묵', 'amount' => '3장'],
                    ['name' => '간장', 'amount' => '2큰술'],
                    ['name' => '올리고당', 'amount' => '1큰술'],
                    ['name' => '고춧가루', 'amount' => '약간'],
                    ['name' => '대파', 'amount' => '1/2대'],
                ],
                'steps_ko' => [
                    '어묵을 먹기 좋은 크기로 자릅니다.',
                    '팬에 기름을 두르고 어묵을 볶습니다.',
                    '간장, 올리고당, 고춧가루를 넣고 볶습니다.',
                    '대파를 넣고 마무리합니다.',
                ],
                'tags' => ['어묵볶음', '반찬', '도시락', '간편식'],
            ],
            [
                'category' => 'side',
                'title' => 'Gamja Jorim',
                'title_ko' => '감자조림',
                'intro_ko' => '감자를 간장 양념에 조린 달콤짭짤한 밑반찬입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '25분',
                'calories' => 180,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '감자', 'amount' => '3개'],
                    ['name' => '간장', 'amount' => '3큰술'],
                    ['name' => '올리고당', 'amount' => '2큰술'],
                    ['name' => '설탕', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '깨', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '감자를 깍둑 썰어 물에 전분을 뺍니다.',
                    '냄비에 감자와 양념, 물을 넣고 끓입니다.',
                    '중불로 줄여 국물이 자작해질 때까지 졸입니다.',
                    '깨를 뿌려 완성합니다.',
                ],
                'tags' => ['감자조림', '반찬', '밑반찬', '도시락'],
            ],

            // ===== 김치 =====
            [
                'category' => 'kimchi',
                'title' => 'Baechu Kimchi',
                'title_ko' => '배추김치',
                'intro_ko' => '한국의 대표 발효식품. 배추에 고춧가루 양념을 버무려 만듭니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간 이상',
                'calories' => 30,
                'servings' => 20,
                'ingredients_ko' => [
                    ['name' => '배추', 'amount' => '1포기'],
                    ['name' => '굵은소금', 'amount' => '1컵'],
                    ['name' => '고춧가루', 'amount' => '1컵'],
                    ['name' => '젓갈', 'amount' => '3큰술'],
                    ['name' => '마늘', 'amount' => '10쪽'],
                    ['name' => '생강', 'amount' => '1톨'],
                    ['name' => '매실액', 'amount' => '2큰술'],
                    ['name' => '찹쌀풀', 'amount' => '1/2컵'],
                    ['name' => '무', 'amount' => '1/4개'],
                    ['name' => '쪽파', 'amount' => '1줌'],
                ],
                'steps_ko' => [
                    '배추를 반으로 갈라 소금물에 6-8시간 절입니다.',
                    '찹쌀풀을 쑤고 고춧가루, 젓갈, 마늘, 생강을 섞어 양념을 만듭니다.',
                    '무채, 쪽파를 양념에 버무립니다.',
                    '절인 배추 잎 사이사이에 양념소를 넣고 겉잎으로 감쌉니다.',
                    '김치통에 담아 실온에서 1-2일 숙성 후 냉장보관합니다.',
                ],
                'tips_ko' => ['쌀뜨물로 풀을 쑤면 감칠맛이 더 좋습니다.'],
                'tags' => ['배추김치', '김치', '발효식품', '기본반찬'],
            ],
            [
                'category' => 'kimchi',
                'title' => 'Kkakdugi',
                'title_ko' => '깍두기',
                'intro_ko' => '무를 깍둑 썰어 양념에 버무린 김치입니다. 설렁탕, 곰탕에 곁들이면 최고입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 25,
                'servings' => 10,
                'ingredients_ko' => [
                    ['name' => '무', 'amount' => '1개'],
                    ['name' => '고춧가루', 'amount' => '5큰술'],
                    ['name' => '젓갈', 'amount' => '2큰술'],
                    ['name' => '설탕', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '2큰술'],
                    ['name' => '생강', 'amount' => '약간'],
                    ['name' => '대파', 'amount' => '1대'],
                ],
                'steps_ko' => [
                    '무를 2cm 크기로 깍둑 썰어 소금에 절입니다.',
                    '30분 후 물기를 빼고 양념을 넣어 버무립니다.',
                    '통에 담아 실온에서 하루 숙성합니다.',
                    '냉장보관하며 먹습니다.',
                ],
                'tags' => ['깍두기', '김치', '무김치', '발효식품'],
            ],
            [
                'category' => 'kimchi',
                'title' => 'Pa Kimchi',
                'title_ko' => '파김치',
                'intro_ko' => '쪽파로 담근 향긋한 김치입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 20,
                'servings' => 8,
                'ingredients_ko' => [
                    ['name' => '쪽파', 'amount' => '2단'],
                    ['name' => '고춧가루', 'amount' => '4큰술'],
                    ['name' => '멸치액젓', 'amount' => '3큰술'],
                    ['name' => '찹쌀풀', 'amount' => '1/4컵'],
                    ['name' => '마늘', 'amount' => '5쪽'],
                ],
                'steps_ko' => [
                    '쪽파를 깨끗이 씻어 다듬습니다.',
                    '찹쌀풀에 고춧가루, 액젓, 마늘 등을 섞어 양념을 만듭니다.',
                    '쪽파에 양념을 골고루 발라줍니다.',
                    '반으로 접어 통에 담아 숙성시킵니다.',
                ],
                'tags' => ['파김치', '김치', '반찬'],
            ],

            // ===== 디저트 =====
            [
                'category' => 'dessert',
                'title' => 'Hotteok',
                'title_ko' => '호떡',
                'intro_ko' => '달콤한 흑설탕 소가 들어간 겨울 길거리 간식입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 250,
                'servings' => 6,
                'ingredients_ko' => [
                    ['name' => '밀가루', 'amount' => '2컵'],
                    ['name' => '이스트', 'amount' => '1큰술'],
                    ['name' => '흑설탕', 'amount' => '1/2컵'],
                    ['name' => '계피가루', 'amount' => '1큰술'],
                    ['name' => '잣', 'amount' => '2큰술'],
                    ['name' => '식용유', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '밀가루에 이스트, 따뜻한 물을 넣어 반죽합니다.',
                    '30분간 발효시킵니다.',
                    '흑설탕, 계피, 잣을 섞어 소를 만듭니다.',
                    '반죽에 소를 넣고 동그랗게 빚어 기름에 눌러가며 구워냅니다.',
                ],
                'tips_ko' => ['누를 때 납작하게 해야 안까지 잘 익습니다.'],
                'tags' => ['호떡', '간식', '겨울음식', '길거리음식'],
            ],
            [
                'category' => 'dessert',
                'title' => 'Patbingsu',
                'title_ko' => '팥빙수',
                'intro_ko' => '곱게 간 얼음 위에 팥과 떡, 과일을 올린 여름 디저트입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '15분',
                'calories' => 320,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '우유 얼음', 'amount' => '2컵'],
                    ['name' => '삶은 팥', 'amount' => '1/2컵'],
                    ['name' => '떡', 'amount' => '4-5개'],
                    ['name' => '연유', 'amount' => '2큰술'],
                    ['name' => '과일(딸기 등)', 'amount' => '적당량'],
                    ['name' => '인절미 가루', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '우유를 얼려 곱게 갈아 그릇에 담습니다.',
                    '삶은 팥, 떡을 올립니다.',
                    '연유를 뿌리고 과일을 올립니다.',
                    '인절미 가루를 뿌려 완성합니다.',
                ],
                'tags' => ['팥빙수', '빙수', '여름간식', '디저트'],
            ],
            [
                'category' => 'dessert',
                'title' => 'Songpyeon',
                'title_ko' => '송편',
                'intro_ko' => '추석에 빚는 전통 떡. 솔잎 향이 나는 반달 모양 떡입니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간',
                'calories' => 120,
                'servings' => 10,
                'ingredients_ko' => [
                    ['name' => '쌀가루', 'amount' => '3컵'],
                    ['name' => '깨 소', 'amount' => '1/2컵'],
                    ['name' => '꿀', 'amount' => '2큰술'],
                    ['name' => '솔잎', 'amount' => '1줌'],
                    ['name' => '참기름', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '쌀가루에 뜨거운 물을 넣어 반죽합니다.',
                    '깨에 설탕과 꿀을 섞어 소를 만듭니다.',
                    '반죽을 조금씩 떼어 소를 넣고 반달 모양으로 빚습니다.',
                    '찜기에 솔잎을 깔고 송편을 올려 20분 찝니다.',
                    '참기름을 살짝 발라 완성합니다.',
                ],
                'tags' => ['송편', '추석', '전통떡', '명절음식'],
            ],
            [
                'category' => 'dessert',
                'title' => 'Yakgwa',
                'title_ko' => '약과',
                'intro_ko' => '꿀과 참기름으로 만든 전통 한과입니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간',
                'calories' => 150,
                'servings' => 15,
                'ingredients_ko' => [
                    ['name' => '밀가루', 'amount' => '2컵'],
                    ['name' => '참기름', 'amount' => '3큰술'],
                    ['name' => '꿀', 'amount' => '1/2컵'],
                    ['name' => '생강즙', 'amount' => '1큰술'],
                    ['name' => '계피가루', 'amount' => '1큰술'],
                    ['name' => '식용유', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '밀가루에 참기름을 넣어 보슬보슬하게 섞습니다.',
                    '꿀, 생강즙, 계피를 넣어 반죽합니다.',
                    '틀로 찍거나 모양을 만들어 저온유(120도)에서 튀깁니다.',
                    '꿀 시럽에 담가 하루 재웁니다.',
                ],
                'tags' => ['약과', '한과', '전통과자', '명절음식'],
            ],

            // ===== 분식 =====
            [
                'category' => 'street',
                'title' => 'Twigim',
                'title_ko' => '모듬튀김',
                'intro_ko' => '각종 채소와 해물을 튀긴 바삭한 길거리 간식입니다.',
                'difficulty' => '보통',
                'cook_time' => '25분',
                'calories' => 350,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '고구마', 'amount' => '1개'],
                    ['name' => '새우', 'amount' => '6마리'],
                    ['name' => '깻잎', 'amount' => '10장'],
                    ['name' => '김말이', 'amount' => '5개'],
                    ['name' => '튀김가루', 'amount' => '1컵'],
                    ['name' => '식용유', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '튀김가루에 차가운 물을 넣어 반죽을 만듭니다.',
                    '재료에 반죽을 입힙니다.',
                    '170도 기름에 바삭하게 튀깁니다.',
                    '떡볶이 양념에 찍어 먹으면 더 맛있습니다.',
                ],
                'tags' => ['튀김', '분식', '간식', '길거리음식'],
            ],
            [
                'category' => 'street',
                'title' => 'Sundae',
                'title_ko' => '순대',
                'intro_ko' => '돼지 순대에 당면과 채소를 넣어 쪄낸 한국 전통 길거리 음식입니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간 이상',
                'calories' => 400,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '돼지 소장', 'amount' => '1m'],
                    ['name' => '당면', 'amount' => '1컵'],
                    ['name' => '숙주나물', 'amount' => '1줌'],
                    ['name' => '부추', 'amount' => '1줌'],
                    ['name' => '돼지피', 'amount' => '1/2컵'],
                    ['name' => '찹쌀', 'amount' => '1/2컵'],
                ],
                'steps_ko' => [
                    '소장을 깨끗이 씻어 준비합니다.',
                    '당면, 숙주, 부추, 돼지피, 양념을 섞어 소를 만듭니다.',
                    '소장에 소를 넣고 양쪽을 묶습니다.',
                    '찜통에서 40분간 쪄냅니다.',
                    '먹기 좋게 잘라 소금에 찍어 먹습니다.',
                ],
                'tags' => ['순대', '분식', '길거리음식', '전통음식'],
            ],
            [
                'category' => 'street',
                'title' => 'Hotdog (Korean Corn Dog)',
                'title_ko' => '한국식 핫도그',
                'intro_ko' => '소시지에 반죽을 입혀 바삭하게 튀긴 한국식 핫도그입니다.',
                'difficulty' => '보통',
                'cook_time' => '25분',
                'calories' => 300,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '소시지', 'amount' => '4개'],
                    ['name' => '모짜렐라 치즈', 'amount' => '200g'],
                    ['name' => '핫케이크가루', 'amount' => '1컵'],
                    ['name' => '빵가루', 'amount' => '1컵'],
                    ['name' => '설탕', 'amount' => '2큰술'],
                    ['name' => '식용유', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '소시지와 치즈를 꼬치에 꽂습니다.',
                    '핫케이크 반죽을 입힙니다.',
                    '빵가루를 굴려 입힙니다.',
                    '170도 기름에 노릇하게 튀기고 설탕을 뿌립니다.',
                ],
                'tags' => ['핫도그', '분식', '간식', '길거리음식'],
            ],
            [
                'category' => 'street',
                'title' => 'Mandu',
                'title_ko' => '만두',
                'intro_ko' => '돼지고기와 채소를 넣은 한국식 만두. 찌고, 굽고, 튀겨 먹을 수 있습니다.',
                'difficulty' => '보통',
                'cook_time' => '45분',
                'calories' => 280,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '만두피', 'amount' => '30장'],
                    ['name' => '돼지고기', 'amount' => '200g'],
                    ['name' => '두부', 'amount' => '1/2모'],
                    ['name' => '김치', 'amount' => '1컵'],
                    ['name' => '부추', 'amount' => '1줌'],
                    ['name' => '당면', 'amount' => '1/2컵'],
                ],
                'steps_ko' => [
                    '두부는 물기를 짜고, 당면은 삶아 잘게 자릅니다.',
                    '모든 소 재료를 섞어 양념합니다.',
                    '만두피에 소를 넣고 예쁘게 빚습니다.',
                    '찜기에 넣고 15분 쪄내면 완성입니다.',
                ],
                'tips_ko' => ['한꺼번에 많이 만들어 냉동하면 편합니다.'],
                'tags' => ['만두', '분식', '겨울음식', '명절음식'],
            ],

            // ===== 추가 인기 요리들 =====
            [
                'category' => 'stew',
                'title' => 'Yukgaejang',
                'title_ko' => '육개장',
                'intro_ko' => '소고기와 대파를 넣고 얼큰하게 끓인 보양탕입니다.',
                'difficulty' => '보통',
                'cook_time' => '1시간',
                'calories' => 420,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '소고기(양지)', 'amount' => '300g'],
                    ['name' => '대파', 'amount' => '4대'],
                    ['name' => '숙주나물', 'amount' => '1줌'],
                    ['name' => '고사리', 'amount' => '1줌'],
                    ['name' => '고춧가루', 'amount' => '3큰술'],
                    ['name' => '다진마늘', 'amount' => '2큰술'],
                    ['name' => '계란', 'amount' => '1개'],
                ],
                'steps_ko' => [
                    '소고기를 삶아 육수를 내고 결대로 찢습니다.',
                    '대파, 숙주, 고사리를 준비합니다.',
                    '육수에 고춧가루 양념과 재료를 넣고 끓입니다.',
                    '계란을 풀어 넣고 마무리합니다.',
                ],
                'tags' => ['육개장', '탕', '보양식', '매운음식'],
            ],
            [
                'category' => 'rice',
                'title' => 'Bokkeumbap',
                'title_ko' => '새우볶음밥',
                'intro_ko' => '새우와 채소를 넣어 볶은 간편한 볶음밥입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '15분',
                'calories' => 400,
                'servings' => 1,
                'ingredients_ko' => [
                    ['name' => '밥', 'amount' => '1공기'],
                    ['name' => '새우', 'amount' => '8마리'],
                    ['name' => '계란', 'amount' => '1개'],
                    ['name' => '대파', 'amount' => '1/2대'],
                    ['name' => '간장', 'amount' => '1큰술'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '팬에 기름을 두르고 새우를 볶습니다.',
                    '계란을 넣고 스크램블합니다.',
                    '밥을 넣고 센불에서 볶습니다.',
                    '간장과 참기름으로 간을 하고 대파를 넣어 완성합니다.',
                ],
                'tags' => ['새우볶음밥', '볶음밥', '간편식', '혼밥'],
            ],
            [
                'category' => 'grill',
                'title' => 'Haemul Pajeon',
                'title_ko' => '해물파전',
                'intro_ko' => '해물과 대파를 넣어 바삭하게 부친 전입니다. 비 오는 날 막걸리와 함께!',
                'difficulty' => '보통',
                'cook_time' => '20분',
                'calories' => 350,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '부침가루', 'amount' => '1컵'],
                    ['name' => '대파', 'amount' => '3대'],
                    ['name' => '오징어', 'amount' => '1/2마리'],
                    ['name' => '새우', 'amount' => '6마리'],
                    ['name' => '계란', 'amount' => '1개'],
                    ['name' => '식용유', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '부침가루에 물과 계란을 넣어 반죽을 만듭니다.',
                    '대파를 길게 자르고 해물을 손질합니다.',
                    '팬에 기름을 넉넉히 두르고 반죽을 얇게 폅니다.',
                    '해물과 파를 올리고 앞뒤로 바삭하게 부칩니다.',
                ],
                'tips_ko' => ['찬물로 반죽하면 더 바삭합니다.'],
                'tags' => ['해물파전', '전', '비오는날', '안주'],
            ],
            [
                'category' => 'side',
                'title' => 'Japchae',
                'title_ko' => '멸치볶음',
                'intro_ko' => '고소하고 달콤한 멸치볶음. 밥반찬과 도시락 반찬으로 인기입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '10분',
                'calories' => 120,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '중멸치', 'amount' => '1컵'],
                    ['name' => '간장', 'amount' => '1큰술'],
                    ['name' => '올리고당', 'amount' => '2큰술'],
                    ['name' => '깨', 'amount' => '1큰술'],
                    ['name' => '고추', 'amount' => '1개'],
                ],
                'steps_ko' => [
                    '팬에 기름 없이 멸치를 살짝 볶아 비린내를 제거합니다.',
                    '간장과 올리고당을 넣어 잘 섞습니다.',
                    '고추를 어슷 썰어 넣고 볶습니다.',
                    '깨를 뿌려 완성합니다.',
                ],
                'tags' => ['멸치볶음', '반찬', '밑반찬', '도시락'],
            ],
            [
                'category' => 'stew',
                'title' => 'Seolleongtang',
                'title_ko' => '설렁탕',
                'intro_ko' => '소뼈를 오랜 시간 끓여 만든 뽀얀 국물의 보양탕입니다.',
                'difficulty' => '어려움',
                'cook_time' => '1시간 이상',
                'calories' => 350,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '소사골', 'amount' => '1kg'],
                    ['name' => '양지', 'amount' => '300g'],
                    ['name' => '소면(사리)', 'amount' => '2인분'],
                    ['name' => '대파', 'amount' => '2대'],
                    ['name' => '소금', 'amount' => '적당량'],
                    ['name' => '후추', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '소사골을 찬물에 담가 핏물을 빼고 한 번 삶아 버립니다.',
                    '깨끗한 물을 다시 넣고 센불에서 끓입니다.',
                    '약불로 줄여 6시간 이상 끓여 뽀얀 국물을 냅니다.',
                    '양지를 건져 썰고, 면사리를 넣어 대접합니다.',
                ],
                'tips_ko' => ['압력솥을 사용하면 시간을 단축할 수 있습니다.'],
                'tags' => ['설렁탕', '탕', '보양식', '겨울음식'],
            ],
            [
                'category' => 'noodle',
                'title' => 'Jjamppong',
                'title_ko' => '짬뽕',
                'intro_ko' => '매콤한 해물 국물에 면을 넣은 한국식 중화 면 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 480,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '중화면', 'amount' => '2인분'],
                    ['name' => '오징어', 'amount' => '1/2마리'],
                    ['name' => '새우', 'amount' => '6마리'],
                    ['name' => '홍합', 'amount' => '1/2컵'],
                    ['name' => '양파', 'amount' => '1개'],
                    ['name' => '양배추', 'amount' => '2장'],
                    ['name' => '고춧가루', 'amount' => '2큰술'],
                    ['name' => '두반장', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '팬에 기름을 두르고 고춧가루와 마늘을 볶아 향을 냅니다.',
                    '해물과 채소를 넣고 센불에서 볶습니다.',
                    '물을 넣고 끓여 국물을 만듭니다.',
                    '삶은 면 위에 국물을 부어 완성합니다.',
                ],
                'tags' => ['짬뽕', '면', '중화요리', '매운음식', '해물'],
            ],
            [
                'category' => 'rice',
                'title' => 'Dakjuk',
                'title_ko' => '닭죽',
                'intro_ko' => '닭을 푹 삶아 만든 부드러운 죽. 몸이 아플 때 먹는 보양 음식입니다.',
                'difficulty' => '보통',
                'cook_time' => '1시간',
                'calories' => 280,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '닭', 'amount' => '1/2마리'],
                    ['name' => '쌀', 'amount' => '1컵'],
                    ['name' => '당근', 'amount' => '1/3개'],
                    ['name' => '대파', 'amount' => '1대'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '참기름', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '닭을 삶아 육수를 내고 살을 찢습니다.',
                    '쌀을 씻어 참기름에 볶습니다.',
                    '닭 육수를 넣고 쌀이 퍼질 때까지 끓입니다.',
                    '닭살, 당근, 대파를 넣고 소금으로 간합니다.',
                ],
                'tags' => ['닭죽', '죽', '보양식', '환자식'],
            ],
            [
                'category' => 'side',
                'title' => 'Dubu Jorim',
                'title_ko' => '두부조림',
                'intro_ko' => '두부를 간장 양념에 조린 고소한 밥반찬입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '15분',
                'calories' => 150,
                'servings' => 3,
                'ingredients_ko' => [
                    ['name' => '두부', 'amount' => '1모'],
                    ['name' => '간장', 'amount' => '2큰술'],
                    ['name' => '고춧가루', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '대파', 'amount' => '1/2대'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                ],
                'steps_ko' => [
                    '두부를 1cm 두께로 썰어 팬에 노릇하게 부칩니다.',
                    '간장, 고춧가루, 마늘, 물을 섞어 양념장을 만듭니다.',
                    '양념장을 부어 중불에서 자작하게 졸입니다.',
                    '대파와 깨를 뿌려 완성합니다.',
                ],
                'tags' => ['두부조림', '반찬', '밑반찬', '건강식'],
            ],
            [
                'category' => 'grill',
                'title' => 'Dakgangjeong',
                'title_ko' => '닭강정',
                'intro_ko' => '바삭하게 튀긴 닭에 매콤달콤한 소스를 버무린 요리입니다.',
                'difficulty' => '보통',
                'cook_time' => '35분',
                'calories' => 480,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '닭봉', 'amount' => '500g'],
                    ['name' => '전분', 'amount' => '1/2컵'],
                    ['name' => '고추장', 'amount' => '2큰술'],
                    ['name' => '간장', 'amount' => '1큰술'],
                    ['name' => '올리고당', 'amount' => '3큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '식용유', 'amount' => '적당량'],
                ],
                'steps_ko' => [
                    '닭에 전분을 입혀 170도 기름에 바삭하게 튀깁니다.',
                    '한 번 더 튀겨 더 바삭하게 합니다.',
                    '팬에 소스(고추장, 간장, 올리고당, 마늘)를 끓입니다.',
                    '튀긴 닭을 넣어 소스에 버무리고 깨를 뿌립니다.',
                ],
                'tags' => ['닭강정', '치킨', '매콤달콤', '간식'],
            ],
            [
                'category' => 'stew',
                'title' => 'Tteokguk',
                'title_ko' => '떡국',
                'intro_ko' => '설날에 먹는 떡국. 맑은 소고기 국물에 떡을 넣어 끓입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '30분',
                'calories' => 380,
                'servings' => 2,
                'ingredients_ko' => [
                    ['name' => '떡국떡', 'amount' => '300g'],
                    ['name' => '소고기(양지)', 'amount' => '200g'],
                    ['name' => '계란', 'amount' => '1개'],
                    ['name' => '대파', 'amount' => '1대'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '간장', 'amount' => '1큰술'],
                    ['name' => '김가루', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '소고기를 삶아 맑은 육수를 냅니다.',
                    '떡국떡을 넣고 끓입니다.',
                    '떡이 떠오르면 간장과 마늘로 간을 합니다.',
                    '계란을 풀어 넣고 대파, 김가루를 올립니다.',
                ],
                'tips_ko' => ['떡을 미리 물에 불려두면 더 빨리 익습니다.'],
                'tags' => ['떡국', '설날', '명절음식', '한식'],
            ],
            [
                'category' => 'street',
                'title' => 'Bungeoppang',
                'title_ko' => '붕어빵',
                'intro_ko' => '붕어 모양 틀에 반죽과 팥앙금을 넣어 구운 겨울 간식입니다.',
                'difficulty' => '보통',
                'cook_time' => '30분',
                'calories' => 180,
                'servings' => 6,
                'ingredients_ko' => [
                    ['name' => '밀가루', 'amount' => '1컵'],
                    ['name' => '베이킹파우더', 'amount' => '1큰술'],
                    ['name' => '계란', 'amount' => '1개'],
                    ['name' => '우유', 'amount' => '1/2컵'],
                    ['name' => '팥앙금', 'amount' => '1컵'],
                ],
                'steps_ko' => [
                    '밀가루, 베이킹파우더, 계란, 우유를 섞어 반죽합니다.',
                    '붕어빵 틀을 예열합니다.',
                    '반죽을 절반 넣고 팥앙금을 올립니다.',
                    '나머지 반죽을 올리고 뚜껑을 닫아 4-5분 굽습니다.',
                ],
                'tags' => ['붕어빵', '간식', '겨울음식', '길거리음식'],
            ],
            [
                'category' => 'side',
                'title' => 'Kongnamul Muchim',
                'title_ko' => '콩나물무침',
                'intro_ko' => '콩나물을 참기름과 마늘로 무친 기본 반찬입니다.',
                'difficulty' => '쉬움',
                'cook_time' => '10분',
                'calories' => 50,
                'servings' => 4,
                'ingredients_ko' => [
                    ['name' => '콩나물', 'amount' => '1봉'],
                    ['name' => '참기름', 'amount' => '1큰술'],
                    ['name' => '다진마늘', 'amount' => '1큰술'],
                    ['name' => '소금', 'amount' => '약간'],
                    ['name' => '깨', 'amount' => '약간'],
                    ['name' => '대파', 'amount' => '약간'],
                ],
                'steps_ko' => [
                    '콩나물을 깨끗이 씻어 뚜껑을 닫고 삶습니다.',
                    '찬물에 헹궈 물기를 뺍니다.',
                    '참기름, 마늘, 소금, 깨로 무칩니다.',
                ],
                'tips_ko' => ['삶을 때 뚜껑을 열면 비린내가 나니 꼭 닫아주세요.'],
                'tags' => ['콩나물무침', '나물', '반찬', '기본반찬'],
            ],
        ];

        // ── 3. 레시피 데이터 삽입 ──
        // 기본 user_id = 1 (관리자)
        $userId = DB::table('users')->first()?->id ?? 1;

        foreach ($recipes as $r) {
            $catId = $categoryMap[$r['category']] ?? null;
            if (!$catId) continue;

            // 이미 같은 title_ko가 있으면 skip
            if (RecipePost::where('title_ko', $r['title_ko'])->exists()) continue;

            RecipePost::create([
                'category_id'    => $catId,
                'user_id'        => $userId,
                'title'          => $r['title'] ?? $r['title_ko'],
                'title_ko'       => $r['title_ko'],
                'intro'          => $r['intro'] ?? $r['intro_ko'],
                'intro_ko'       => $r['intro_ko'] ?? null,
                'difficulty'     => $r['difficulty'] ?? '보통',
                'cook_time'      => $r['cook_time'] ?? '30분',
                'calories'       => $r['calories'] ?? null,
                'servings'       => $r['servings'] ?? 2,
                'ingredients'    => $r['ingredients'] ?? $r['ingredients_ko'],
                'ingredients_ko' => $r['ingredients_ko'] ?? null,
                'steps'          => $r['steps'] ?? $r['steps_ko'],
                'steps_ko'       => $r['steps_ko'] ?? null,
                'tips'           => $r['tips'] ?? $r['tips_ko'],
                'tips_ko'        => $r['tips_ko'] ?? null,
                'tags'           => $r['tags'] ?? [],
                'image_url'      => $r['image_url'] ?? null,
                'source'         => 'ai',
            ]);
        }

        $this->command->info('Korean recipe seeder completed: ' . count($recipes) . ' recipes processed.');
    }
}
